### ISSUE TITLE
Setup CI for Nightfall

### ISSUE THREAD

**Issue by ChaitanyaKonda** [EYBlockchain/nightfall#148]
# Description
Setup Travis CI or Github actions. This will need to run integration tests `./nightfall-test` for every PR.

#### Expected behaviour
Every PR to be tested

**Comment by fulldecent** [comment]
This issue is not solvable in its current form.

Travis CI has a build timeout of 50 minutes, per https://docs.travis-ci.com/user/customizing-the-build/#build-timeouts

The GitHub Actions timeouts have not been publicly announced and the program is still is in beta but it is reasonable to expect they will have similar timeouts as Travis.

As such the integration test cannot be run in this way.

Workable options include:

1. Create a unit testing script and run that from CI for now, table remaining scope of this issue for a later date
2. Create a separate procedure for running integration testing trigger that formally before Nightfall releases
3. Make the ZKP code simpler so that it runs 10x faster

These are all good options and I recommend them in order of preference above.

**Comment by ChaitanyaKonda** [comment]
@fulldecent Github actions seem to have sufficient timeout setting. Had successful run [here](https://github.com/EYBlockchain/nightfall/commit/5791d99550ab39280732b99a719bc3f1d5de7b13/checks)

**Comment by fulldecent** [comment]
Wow, excellent. This is way faster processing than I expected!
