### ISSUE TITLE
Transferring full balance of OpsCoin commitments results in an error

### ISSUE THREAD

**Issue by jwhelan72** [EYBlockchain/nightfall#32]
1. I have two commitments (15 & 10) for OpsCoin

![image](https://user-images.githubusercontent.com/1807284/59153018-9696e900-8a50-11e9-9480-ebd079a0ef6e.png)

2. Trying to transfer full balance to B results in an error

![image](https://user-images.githubusercontent.com/1807284/59153016-7ebf6500-8a50-11e9-95a4-def3ffba578a.png)

**Comment by ChaitanyaKonda** [comment]
The ERC-20 commitment transfer currently takes two commitment inputs and creates two commitment outputs. For example, Alice owns commitments C and D of value 15 and 10. She wishes to send Bob, 12. In this case, two output commitments E and F are created with values 12 and 3 held within. In your case since you want to transfer all 15 to Bob, commitment E will hold 15 while F would hold 0. But you can see, the POST call has a body that doesn't have an F value at all. The Proof won't compute because F is not being sent from front end. 

This can be rectified by 
- changing the front end to create a 0 commitment in situations such as these but that means Alice would hold a commitment that has no value at all and hence is unusable. 
- the front end could ignore displaying 0 value tokens to maintain a good UI.

**Comment by jwhelan72** [comment]
Understood.  Two inputs = output + change.  That was not clear to me.

**Comment by asishap** [comment]
@jwhelan72 
As per your example 
two inputs are 15 and 10
output = 25
change = 0
ie Two inputs (15+10) =  25(output transfer value) + 0 (change).
In frontend, it is not handled for change value `0`. Will fix that issue soon.
