### ISSUE TITLE
[Question] Could the FTokenShield contract be generalized to shield multiple ERC20 ?

### ISSUE THREAD

**Issue by rrodriguezreche** [EYBlockchain/nightfall#347]
Hi, this is more of a question than an issue. If anything and in case there is a chat (telegram, slack or gitter, whatever), I 'd suggest adding it to the main readme :)

My understanding of zk proofs is still limited, but I find this fascinating. Could the FTokenShield contract hold multiple ERC20 tokens, without changing the current ZK circuits of the shield? For someone who is experienced in solidity but still new for ZK, would this be attainable?

Thanks!

**Comment by iAmMichaelConnor** [comment]
Hi @rrodriguezreche thanks for the question!

FTokenShield could (in theory) definitely hold ERC-20 tokens from multiple ERC-20 contracts. There's an open issue here: https://github.com/EYBlockchain/nightfall/issues/237

It just hasn't been implemented by anyone yet :)

The database, zero-knowledge proofs, and smart contracts would need to be updated to allow multiple ERC-20 contract addresses to be handled.

There's also an even more generalised suggestion here: https://github.com/EYBlockchain/nightfall/issues/250 where a shield contract could be edited so that the Merkle Tree holds tokens of any kind (i.e. from any ERC token standard). This would be cool to see also.

**Comment by rrodriguezreche** [comment]
Hi @iAmMichaelConnor , awesome, thank you for pointing me out to those issues.

I was hoping not to get my hands too dirty with ZK, but I guess I will.

Let me close this issue and keep the discussion in the links you provided :) Thank you again.
